routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index');
Route::get('blog/{id}', 'BlogController@show');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function(){
    Route::get('signin', 'SignController@index')->name('admin_signin');
    Route::post('signin', 'SignController@store')->name('admin_signin');
    Route::delete('signout', 'SignController@destroy')->name('admin_signout');
});

Auth::routes();

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'prefix' => 'admin'], function () {
    Route::get('/', 'DashboardController@index')->name('admin_home');
    Route::get('get_tags', 'TagsController@getTags')->name('get_tags');
    Route::resource('category', 'CategoryController');
    Route::resource('tags', 'TagsController');
    Route::resource('article', 'ArticleController');
    Route::patch('update_publish/{id}', 'ArticleController@update_publish')->name('update_publish');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = "categories";

    protected $fillable = [
        'name', 'parent_id', 'describe'
    ];


    public function children() {
        return $this->hasMany('App\Models\Category','parent_id','id') ;
    }

    public function parent(){
        return $this->belongsTo('App\Models\Category', 'parent_id', 'id');
    }

    public function articles(){
        return $this->hasMany('App\Models\Article', 'category_id', 'id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::all();
        return view('admin.category.list', compact('categories'));
    }

    public function create()
    {   
        $categories = Category::all();
        return view('admin.category.create', compact('categories'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name'  => 'required|max:50|unique:categories',
        ]);

        Category::create([
            'name' =>  $request->name,
            'parent_id' => $request->parent_id,
            'describe' => $request->describe,
        ]);

        session()->flash('success', '创建Category成功');
        return redirect()->back();
    }

    public function edit($id)
    {
        $category = Category::findOrFail($id);
        $category->categories = Category::all();
        return view('admin.category.edit', compact('category'));
    }

    public function update($id, Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:50',
        ]);

        $category = Category::findOrFail($id);
        $category->name = $request->name;
        $category->parent_id = $request->parent_id;
        $category->describe = $request->describe;

        $category->update();

        session()->flash('success', '更新Category成功');

        return redirect()->route('category.index');
    }

    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();
        session()->flash('success', '创建Category成功');
        return redirect()->back();
    }

}

resources/views/admin/category/create.blade.php
@extends('admin.layouts.default')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                Catepory Manage
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Catepory Manage</li>
                <li class="active">Post Catepory</li>
            </ol>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Post Catepory</h3>
                        </div>

                        <div class="box-body">
                            @include('shared.messages')
                            @include('shared.errors')

                            <form role="form" method="POST" action="{{ route('category.store') }}">
                                {{ csrf_field() }}
                                    <div class="form-group">
                                        <label>Catepory Name</label>
                                        <input type="text" name="name" class="form-control" placeholder="Catepory Name">
                                    </div>
                                    <div class="form-group">
                                        <label>Catepory Parent</label>
                                        <select multiple class="form-control" name="parent_id">
                                            <option selected="selected" value="0">NONE</option>
                                            @foreach($categories as $category)
                                                @if($category->parent_id === 0)
                                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                                    @include('shared.select_tree', ['children' => $category->children])
                                                @endif
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label>Catepory Describe</label>
                                        <input type="text" name="describe" class="form-control" placeholder="Category Describe">
                                    </div>
                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary fa fa-save"> Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.layouts.default')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                Catepory Manage
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Catepory Manage</li>
                <li class="active">Post Catepory</li>
            </ol>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Post Catepory</h3>
                        </div>

                        @include('shared.messages')
                        @include('shared.errors')

                        <form role="form" method="POST" action="{{ route('category.update', $category->id) }}">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            <div class="box-body">
                                <div class="form-group">
                                    <label>Catepory Name</label>
                                    <input type="text" name="name" value="{{ $category->name }}" class="form-control" placeholder="Catepory Name">
                                </div>
                                <div class="form-group">
                                    <label>Catepory Parent</label>
									<select multiple class="form-control" name="parent_id">
										<option selected="selected" value="0">NONE</option>
                                        @foreach($category->categories as $cate)
                                            @if($cate->parent_id === 0 and $category->id != $cate->id)
                                                <option value="{{ $cate->id }}">{{ $cate->name }}</option>
                                                @include('shared.select_tree', ['children' => $cate->children])
                                            @endif
                                        @endforeach
									</select>
                                </div>
                                <div class="form-group">
                                    <label>Catepory Describe</label>
                                    <input type="text" name="describe" class="form-control" value="{{ $category->describe }}" placeholder="Category Describe">
                                </div>
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary fa fa-save"> Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/category/list.blade.php
@extends('admin.layouts.default')

@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Category Manage
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Category Manage</li>
            <li class="active">Category List</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Tags List</h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-body table-responsive no-padding">
                        <table id="category_list" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Category</th>
                                    <th>Parent</th>
                                    <th>Describe</th>
                                    <th>CreateTime</th>
                                    <th>Operation</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <td>{{ $category->id }}</td>
                                    <td>{{ $category->name }}</td>
                                    <td>
                                    @if($category->parent_id != 0)
                                    {{ $category->parent->name}}
                                    @endif
                                    </td>
                                    <td>{{ $category->describe }}</td>
                                    <td>{{ $category->created_at }}</td>
                                    <td>
                                        <form action="{{ route('category.edit', $category->id) }}" style="display: inline;">
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-warning btn-xs">Edit</button>
                                        </form>
                                        <form action="{{ route('category.destroy', $category->id) }}" method="POST" style="display: inline;">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <button type="submit" class="btn btn-danger btn-xs">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- DataTables -->
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<script>
    $(function() {
        $('#category_list').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false
        });
    });
</script>
@endsection

resources/views/admin/category/show.blade.php
@extends('admin.layouts.default')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                Catepory Manage
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Catepory Manage</li>
                <li class="active">Post Catepory</li>
            </ol>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Post Catepory</h3>
                        </div>

                        @include('shared.messages')
                        @include('shared.errors')

                        <form role="form" method="POST" action="{{ route('category.store') }}">
                            {{ csrf_field() }}

                            <div class="box-body">
                                <div class="form-group">
                                    <label>Catepory Name</label>
                                    <input type="text" name="name" class="form-control" placeholder="Catepory Name">
                                </div>
                                <div class="form-group">
                                    <label>Catepory Parent</label>
                                    <select multiple class="form-control" name="parent_id">
                                        <option selected="selected" value="0">NONE</option>
                                        @foreach($categories as $category)
                                            @if($category->parent_id === 0)
                                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                                @include('shared.tree', ['children' => $category->children])
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Catepory Describe</label>
                                    <input type="text" name="describe" class="form-control" placeholder="Catepory Describe">
                                </div>
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary fa fa-save"> Save</button>
                                <form action="">
                                    <button type="submit" class="btn btn-primary fa fa-remove"> Delete</button>
                                </form>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection