routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index');
Route::get('blog/{id}', 'BlogController@show');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function(){
    Route::get('signin', 'SignController@index')->name('admin_signin');
    Route::post('signin', 'SignController@store')->name('admin_signin');
    Route::delete('signout', 'SignController@destroy')->name('admin_signout');
});

Auth::routes();

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'prefix' => 'admin'], function () {
    Route::get('/', 'DashboardController@index')->name('admin_home');
    Route::get('get_tags', 'TagsController@getTags')->name('get_tags');
    Route::resource('category', 'CategoryController');
    Route::resource('tags', 'TagsController');
    Route::resource('article', 'ArticleController');
    Route::patch('update_publish/{id}', 'ArticleController@update_publish')->name('update_publish');
});

app/Models/Article.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use GrahamCampbell\Markdown\Facades\Markdown;

class Article extends Model
{
    protected $table = "articles";

    protected $fillable = [
        'title', 'tag_id', 'category_id', 'content', 'hits', 'is_publish', 'author', 'source'
    ];

    public function category()
    {
        return $this->belongsTo('App\Models\Category', 'category_id');
    }
    
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Tag;
use App\Models\Article;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\ArticleRequest;
use League\HTMLToMarkdown\HtmlConverter;
use Parsedown;

class ArticleController extends Controller
{
    public function index()
    {
        $articles = Article::all();
        foreach ($articles as &$article) {
            $article->category = Category::findOrFail($article->category_id)->name;

            $tags = [];
            $tags_arr = explode(',', $article->tag_id);
            foreach ($tags_arr as $tag_id) {
                $tag = Tag::findOrFail($tag_id);
                array_push($tags, $tag->name);
            }
            
            $article->tag = implode(',', $tags);
        }
        
        return view('admin.articles.list', compact('articles'));
    }

    public function create()
    {
        $categories = Category::all();
        return view('admin.articles.create', ['categories' => $categories]);
    }

    public function store(ArticleRequest $request)
    {
        $Parsedown = new Parsedown();
        $result = Article::create([
            'title' => $request->input('title'),
            'author' => $request->input('author', 'Tandy'),
            'source' => $request->input('source'),
            'category_id' => intval($request->category_id),
            'tag_id' => $request->tag_id,
            'content' => $Parsedown->text($request->input('content'))
        ]);

        session()->flash('success', '发布成功');
        return redirect()->back();
    }

    public function update_publish($id, Request $request)
    {
        $article = Article::findOrFail($id);
        $article->is_publish = $request->publish;
        $article->update();

        return redirect()->back();
    }


    public function edit($id)
    {
        $article = Article::findOrFail($id);
        $article->categories = Category::all();
        
        $tags_data = [];
        $tags_arr = explode(',', $article->tag_id);
        foreach ($tags_arr as $tag_id) {
            $tag = Tag::findOrFail($tag_id);
            array_push($tags_data, [
                'id' => $tag->id,
                'name' => $tag->name,
            ]);
        }

        $article->tags = json_encode($tags_data);

        $converter = new HtmlConverter();
        $content = $converter->convert($article->content);
        $article->content = $content;

        return view('admin.articles.edit', compact('article'));
    }

    public function update($id, ArticleRequest $request)
    {
        $article = Article::findOrFail($id);

        $Parsedown = new Parsedown();
        $data = [];
        $data = [
            'title' => $request->title,
            'author' => $request->author,
            'source' => $request->source,
            'category_id' => $request->category_id,
            'tag_id' => $request->tag_id,
            'content' => $Parsedown->text($request->content)
        ];

        $article->update($data);

        session()->flash('success', "更新成功");

        return redirect()->route('article.index');
    }

    public function destroy($id)
    {
        $article = Article::findOrFail($id);
        $article->delete();

        session()->flash('success', '删除成功');

        return redirect()->back();
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.layouts.default')
@section('css')
<link rel="stylesheet" href="{{ asset('assets/plugins/tagsinput/bootstrap-tagsinput.css') }}">
<link rel="stylesheet" href="{{ asset('assets/plugins/tagsinput/bootstrap-tagsinput-typeahead.css') }}">
{!! editor_css() !!}
@endsection

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                Article Manage
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Article Manage</li>
                <li class="active">Post Article</li>
            </ol>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Post Article</h3>
                        </div>

                        <div class="box-body">
                            @include('shared.messages')
                            @include('shared.errors')
                            
                            <form role="form" method="POST" action="{{ route('article.store') }}">
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label>Article Title</label>
                                    <input type="text" name="title" class="form-control" placeholder="Article Title">
                                </div>
                                <div class="form-group">
                                    <label>Article Author</label>
                                    <input type="text" name="author" class="form-control" placeholder="Article Author">
                                </div>
                                <div class="form-group">
                                    <label>Article Source</label>
                                    <input type="text" name="source" class="form-control" placeholder="Article Source">
                                </div>
                                <div class="form-group">
                                    <label>Catepory Parent</label>
                                    <select multiple class="form-control" name="category_id">
                                        <option selected="selected" value="0">NONE</option>
                                        @foreach($categories as $category)
                                            @if($category->parent_id === 0)
                                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                                @include('shared.select_tree', ['children' => $category->children])
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Article Tags</label>
                                    <span class="form-group">
                                        <input type="text" name="tag_id" id="tags" class="form-control" placeholder="Article Tags">
                                    </span>
                                </div>
                                <div class="form-group">
                                    <label>Article Content</label>
                                    <div id="mdeditor">
                                        <textarea class="form-control" name="content" style="display:none;"></textarea>
                                    </div>
                                </div>
                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <script src="{{ asset('assets/plugins/tagsinput/bootstrap-tagsinput.js') }}"></script>
    <script src="{{ asset('assets/plugins/tagsinput/typeahead.jquery.js') }}"></script>
    <script src="{{ asset('assets/plugins/tagsinput/typeahead.bundle.js') }}"></script>
    <script src="{{ asset('assets/plugins/tagsinput/angular.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/tagsinput/bootstrap-tagsinput-angular.min.js') }}"></script>
    <script>
        "use strict"
        
        var tags = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            prefetch: '{{ route("get_tags") }}'
        });
        tags.initialize();

        $("#tags").tagsinput({
            itemValue: 'value',
            itemText: 'text',
            typeaheadjs: {
                name: 'tags',
                displayKey: 'text',
                source: tags.ttAdapter(),
            },
        });
    </script>

    {!! editor_js() !!}
    {!! editor_config('mdeditor') !!}
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.default')
@section('css')
<link rel="stylesheet" href="{{ asset('assets/plugins/tagsinput/bootstrap-tagsinput.css') }}">
<link rel="stylesheet" href="{{ asset('assets/plugins/tagsinput/bootstrap-tagsinput-typeahead.css') }}">
{!! editor_css() !!}
@endsection

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                Article Manage
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Article Manage</li>
                <li class="active">Post Article</li>
            </ol>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Post Article</h3>
                        </div>

                        <div class="box-body">
                            @include('shared.messages')
                            @include('shared.errors')
                            
                            <form role="form" method="POST" action="{{ route('article.update', $article->id) }}">
                                {{ method_field('PATCH') }}
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label>Article Title</label>
                                    <input type="text" name="title" class="form-control" placeholder="Article Title" value="{{ $article->title }}">
                                </div>
                                <div class="form-group">
                                    <label>Article Author</label>
                                    <input type="text" name="author" class="form-control" placeholder="Article Author" value="{{ $article->author }}">
                                </div>
                                <div class="form-group">
                                    <label>Article Source</label>
                                    <input type="text" name="source" class="form-control" placeholder="Article Source" value="{{ $article->source }}">
                                </div>
                                <div class="form-group">
                                    <label>Catepory Parent</label>
                                    <select multiple class="form-control" name="category_id" id="category_id">
                                        <option value="0">NONE</option>
                                        @foreach($article->categories as $category)
                                            @if($category->parent_id === 0)
                                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                                @include('shared.select_tree', ['children' => $category->children])
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Article Tags</label>
                                    <span class="form-group">
                                        <input type="text" name="tag_id" id="tags" class="form-control" placeholder="Article Tags">
                                    </span>
                                </div>
                                <div class="form-group">
                                    <label>Article Content</label>
                                    <div id="mdeditor">
                                        <textarea class="form-control" name="content" style="display:none;">{{ $article->content }}</textarea>
                                    </div>
                                </div>
                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <script src="{{ asset('assets/plugins/tagsinput/bootstrap-tagsinput.js') }}"></script>
    <script src="{{ asset('assets/plugins/tagsinput/typeahead.jquery.js') }}"></script>
    <script src="{{ asset('assets/plugins/tagsinput/typeahead.bundle.js') }}"></script>
    <script src="{{ asset('assets/plugins/tagsinput/angular.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/tagsinput/bootstrap-tagsinput-angular.min.js') }}"></script>
    <script>
        "use strict";
        var tags = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            prefetch: '{{ route("get_tags") }}'
        });
        tags.initialize();

        var tags_input = $("#tags");
        tags_input.tagsinput({
            itemValue: 'value',
            itemText: 'text',
            typeaheadjs: {
                name: 'tags',
                displayKey: 'text',
                source: tags.ttAdapter(),
            },
        });

        var data = {!! $article->tags !!};
        $.each(data, function(){
            var value = this.id;
            var text = this.name;
            tags_input.tagsinput('add', {'value': value, 'text': text});
        });

        $("#category_id option").each(function(){
            if($(this).val() == {{ $article->category_id }}){
                $(this).attr('selected', 'selected');
            }
        });
    </script>

    {!! editor_js() !!}
    {!! editor_config('mdeditor') !!}
@endsection

resources/views/admin/articles/list.blade.php
@extends('admin.layouts.default')

@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Article Manage
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Article Manage</li>
            <li class="active">Article List</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Articles List</h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="s·ubmit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-body">
                        @include('shared.messages')
                        <table id="aritcle_list" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Title</th>
                                    <th>Author</th>
                                    <th>Source</th>
                                    <th>Tag</th>
                                    <th>Category</th>
                                    <th>Hits</th>
                                    <th>Status</th>
                                    <th>Created_at</th>
                                    <th>Updated_at</th>
                                    <th>Operation</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($articles as $article)
                                <tr>
                                    <td>{{ $article->id }}</td>
                                    <td>{{ str_limit($article->title, 10, '...') }}</td>
                                    <td>{{ $article->author}}</td>
                                    <td>{{ str_limit($article->source, 10, '...') }}</td>
                                    <td>{{ str_limit($article->tag, 10, '...') }}</td>
                                    <td>{{ $article->category }}</td>
                                    <td>{{ $article->hits }}</td>
                                    <td>
                                        <form method="post" action="{{ route('update_publish', $article->id) }}">
                                            {{ method_field('PATCH') }}
                                            {{ csrf_field() }}
                                            @if($article->is_publish == 1)
                                            <input type="text" value="0" name="publish" hidden>
                                            <button type="submit" class="btn btn-block btn-success btn-xs">Publish</button>
                                            @else
                                            <input type="text" value="1" name="publish" hidden>
                                            <button type="submit" class="btn btn-block btn-danger btn-xs">No Publish</button>
                                            @endif
                                            </form>
                                    </td>
                                    <td>{{ strstr($article->created_at, " ", true) }}</td>
                                    <td>{{ strstr($article->updated_at, " ", true) }}</td>
                                    <td>
                                        <form action="{{ route('article.edit', $article->id) }}" style="display: inline;">
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-warning btn-xs">Edit</button>
                                        </form>
                                        <form action="{{ route('article.destroy', $article->id) }}" method="POST" style="display: inline;">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <button type="submit" class="btn btn-danger btn-xs">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- DataTables -->
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>

<script>
    $(function () {
        $('#aritcle_list').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false
        });
    });
</script>
@endsection