routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index');
Route::get('blog/{id}', 'BlogController@show');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function(){
    Route::get('signin', 'SignController@index')->name('admin_signin');
    Route::post('signin', 'SignController@store')->name('admin_signin');
    Route::delete('signout', 'SignController@destroy')->name('admin_signout');
});

Auth::routes();

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'prefix' => 'admin'], function () {
    Route::get('/', 'DashboardController@index')->name('admin_home');
    Route::get('get_tags', 'TagsController@getTags')->name('get_tags');
    Route::resource('category', 'CategoryController');
    Route::resource('tags', 'TagsController');
    Route::resource('article', 'ArticleController');
    Route::patch('update_publish/{id}', 'ArticleController@update_publish')->name('update_publish');
});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $table = "tags";

    protected $fillable = [
        'name', 'describe'
    ];
}

app/Http/Controllers/Admin/TagsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TagsController extends Controller
{

    public function index()
    {
        $tags = Tag::all();
        return view('admin.tags.list', compact('tags'));
    }

    public function create()
    {
        return view('admin.tags.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name'  =>  'required|max:255|unique:tags',
        ]);

        Tag::create([
            'name' => $request->name,
        ]);

        session()->flash('success', '创建Tag成功！');
        return redirect()->back();
    }

    public function edit($id)
    {
        $tags = Tag::findOrFail($id);
        return view('admin.tags.edit', compact('tags'));
    }

    public function update($id, Request $request)
    {
        $tags = Tag::findOrFail($id);
        $tags->name = $request->name;
        $tags->update();

        session()->flash('success', 'Tag更新成功');
        return redirect()->route('tags.index');
    }

    public function destroy($id)
    {
        $tag = Tag::findOrFail($id);
        $tag->delete();

        session()->flash('success', '删除tag成功');
        return redirect()->back();
    }

    public function getTags()
    {
        $tags = Tag::all();
        $tags_data = [];
        foreach ($tags as $tag) {
            array_push($tags_data, [
                "value" => $tag->id,
                "text" => $tag->name,
            ]);
        }

        return response()->json($tags_data);
    }
}

resources/views/admin/tags/create.blade.php
@extends('admin.layouts.default')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                Tags Manage
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Tags Manage</li>
                <li class="active">Post Tags</li>
            </ol>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Post Tags</h3>
                        </div>

                        <div class="box-body">
                            @include('shared.messages')
                            @include('shared.errors')

                            <form role="form" method="POST" action="{{ route('tags.store') }}">
                                {{ csrf_field() }}
                                    <div class="form-group">
                                        <label>Tags Name</label>
                                        <input type="text" name="name" class="form-control" placeholder="Tags Name">
                                    </div>
                                    <div class="form-group">
                                        <label>Tags Describe</label>
                                        <input type="text" name="describe" class="form-control" placeholder="Tags Describe">
                                    </div>
                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary fa fa-floppy-o"> Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layouts.default')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                Tag Manage
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Tag Manage</li>
                <li class="active">Post Tag</li>
            </ol>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Post Tag</h3>
                        </div>

                        @include('shared.messages')
                        @include('shared.errors')

                        <form role="form" method="POST" action="{{ route('tags.update', $tags->id) }}">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            <div class="box-body">
                                <div class="form-group">
                                    <label>Tags Name</label>
                                    <input type="text" name="name" value="{{ $tags->name }}" class="form-control" placeholder="Tags Name">
                                </div>
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary fa fa-save"> Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/tags/list.blade.php
@extends('admin.layouts.default')

@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Tags Manage
            <small></small>
        </h1>

        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Tags Manage</li>
            <li class="active">Tags List</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Tags List</h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                                <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-body table-responsive no-padding">
                        <table id="tags_list" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Tags</th>
                                <th>CreateTime</th>
                                <th>Operation</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($tags as $tag)
                            <tr>
                                <td>{{ $tag->id }}</td>
                                <td>{{ $tag->name }}</td>
                                <td>{{ $tag->created_at }}</td>
                                <td>
                                    <form action="{{ route('tags.edit', $tag->id) }}" style="display: inline;">
                                        {{ csrf_field() }}
                                        <button type="submit" class="btn btn-warning btn-xs">Edit</button>
                                    </form>
                                    <form action="{{ route('tags.destroy', $tag->id) }}" method="POST" style="display: inline;">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button type="submit" class="btn btn-danger btn-xs">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- DataTables -->
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>

<script>
    $(function() {
        $('#tags_list').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false
        });
    });
</script>
@endsection